conda-forge/clang-compiler-activation-feedstock

- recipe/meta.yaml
> Add clang_bootstrap

- recipe/meta.yaml
> update version to 8.0.1

- .azure-pipelines/azure-pipelines-osx.yml
- .gitattributes
- README.md
- recipe/meta.yaml
Hi! This is the friendly automated conda-forge-webservice.
I've rerendered the recipe as instructed in #3.
Here's a checklist to do before merging.
Fixes #3
> MNT: rerender

- .azure-pipelines/azure-pipelines-osx.yml
- .github/CODEOWNERS
- README.md
- conda-forge.yml
- recipe/meta.yaml
> Bump build number

- recipe/meta.yaml
> Bump build number again

- recipe/meta.yaml
> Update to 9.0.0

- README.md
- recipe/meta.yaml
Depends on https://github.com/conda-forge/llvmdev-feedstock/pull/81
Checklist
@conda-forge-admin, please rerender
> Update to 9.0.1

- recipe/activate-clang++.sh
- recipe/activate-clang.sh
- recipe/deactivate-clang++.sh
- recipe/deactivate-clang.sh
- recipe/meta.yaml
> Don't uppercase env variables

- recipe/activate-clang.sh
- recipe/deactivate-clang.sh
- recipe/meta.yaml
> Make sure activation works in envs with nounset

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_target_platformlinux-64.yaml
- .ci_support/osx_64_.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- README.md
- recipe/activate-clang++.sh
- recipe/activate-clang.sh
- recipe/build.sh
- recipe/deactivate-clang++.sh
- recipe/deactivate-clang.sh
- recipe/meta.yaml
> Set CC_FOR_BUILD and CXX_FOR_BUILD

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0target_platformlinux-64.yaml
- .ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0target_platformlinux-64.yaml
- .ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0target_platformosx-64.yaml
- .ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0target_platformosx-64.yaml
- .ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0target_platformosx-arm64.yaml
- .ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0target_platformosx-arm64.yaml
- README.md
- recipe/build.sh
- recipe/conda_build_config.yaml
- recipe/install-clang.sh
- recipe/install-clangxx.sh
- recipe/meta.yaml
> Add a CBUILD-clang

- recipe/activate-clang.sh
- recipe/install-clang-bootstrap.sh
- recipe/meta.yaml
> unset CONDA_BUILD_SYSROOT during test phase if it doesn't exist

- recipe/activate-clang.sh
- recipe/build.sh
- recipe/conda_build_config.yaml
- recipe/deactivate-clang.sh
- recipe/meta.yaml
> Add MESON_ARGS

- recipe/activate-clang.sh
- recipe/deactivate-clang.sh
- recipe/meta.yaml
> Fix meson and realloc

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0.yaml
- .ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0.yaml
- .ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0.yaml
- .ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0.yaml
- .ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0.yaml
- .ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0.yaml
- README.md
- recipe/activate-clang.sh
- recipe/meta.yaml
> remove comma, fix #43

- recipe/activate-clang++.sh
- recipe/activate-clang.sh
- recipe/deactivate-clang++.sh
- recipe/deactivate-clang.sh
- recipe/meta.yaml
> Don't use full path to cctools as we don't do it for compilers too

- .ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0.yaml
- .ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0.yaml
- .ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0.yaml
- .ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0.yaml
- .scripts/run_docker_build.sh
- recipe/activate-clang.sh
- recipe/deactivate-clang.sh
- recipe/meta.yaml
Checklist
This PR uses a version of the hack here (https://github.com/conda/conda/issues/7031#issuecomment-560587364) to fix #50. 
cc @ktlim  @cwwalter @erykoff
> BUG make sure to not munge prompt in zsh

- recipe/activate-clang.sh
- recipe/deactivate-clang.sh
- recipe/meta.yaml
> BUG use zsh internal for adding hooks

- recipe/meta.yaml
> update to 11.0.1

- recipe/meta.yaml
Trying to unblock https://github.com/conda-forge/llvmdev-feedstock/pull/115 by [recommendation](https://github.com/conda-forge/llvmdev-feedstock/pull/115#issuecomment-787497658) from @isuruf.
> add ignore_run_exports_from libllvm<ver>

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- conda-forge.yml
- recipe/activate-clang.sh
- recipe/meta.yaml
> remove indr

- recipe/meta.yaml
> use older ld64 and cctools

- recipe/meta.yaml
> remove cctools and ld64 pinning

- recipe/activate-clang.sh
- recipe/meta.yaml
> use CONDA_PREFIX instead of BUILD_PREFIX for non conda-build usage

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.1.yaml
- .ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.1.yaml
- .ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.1.yaml
- .ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.1.yaml
- .ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.1.yaml
- .ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.1.yaml
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> LLVM 16.0.1

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.2.yaml
- .ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.2.yaml
- .ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.2.yaml
- .ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.2.yaml
- .ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.2.yaml
- .ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.2.yaml
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> LLVM 16.0.2

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.3.yaml
- .ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.3.yaml
- .ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.3.yaml
- .ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.3.yaml
- .ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.3.yaml
- .ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.3.yaml
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> LLVM 16.0.3

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.4.yaml
- .ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.4.yaml
- .ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.4.yaml
- .ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.4.yaml
- .ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.4.yaml
- .ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.4.yaml
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> LLVM 16.0.4

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.0.rc3.yaml
- .ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.0.rc3.yaml
- .ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.0.rc3.yaml
- .ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.0.rc3.yaml
- .ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.0.rc3.yaml
- .ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.0.rc3.yaml
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
The PRs marked ** are not strictly speaking necessary for merging this PR, but for LLVM 17.x support in conda-forge.
> LLVM 17.0.0.rc3

- recipe/install-clang-scripts.sh
- recipe/install-clang.sh
- recipe/install-clangxx-scripts.sh
- recipe/install-clangxx.sh
- recipe/meta.yaml
> Add clang_impl packages for packages without activation

- recipe/build.sh
- recipe/meta.yaml
Checklist
Closes https://github.com/conda-forge/clang-compiler-activation-feedstock/issues/90
Closes https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/89
> Don't pass in -fPIE and -Wl,-pie as it's the default now

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.1.yaml
- .ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.1.yaml
- .ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.1.yaml
- .ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.1.yaml
- .ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.1.yaml
- .ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.1.yaml
- README.md
- recipe/conda_build_config.yaml
- recipe/install-clang.sh
- recipe/install-clangxx.sh
```mermaid
---
config:
---
flowchart TD
subgraph core["core dependencies"]
llvmdev["☑ llvmdev"]-->clangdev["☑ clangdev"]
libcxx["☑ libcxx"]-->clangdev
llvmdev["☑ llvmdev"]-->lld["☑ lld"]
clangdev-->compiler-rt["☑ compiler-rt"]
clangdev-->cctools["☑ cctools<br/>(major-only)"]
compiler-rt-->openmp["☑ openmp"]
end
subgraph clangs["other clang compilers"]
clang_linux["☑ clang for linux<br/>(major-only)"]
clang_linux~~~clang_win["☑ clang for windows<br/>(major-only)"]
clang_win~~~r_clang["☑ r_clang<br/>(major-only)"]
end
compiler-rt-->flang
subgraph rest["other LLVM bits"]
mlir-->flang["☐ flang"]
mlir-->mlir-python["☑ mlir-python"]
flang["☐ flang"]-->flang-activation["☐ flang-activation"]
flang-activation~~~libcxx-testing["☑ libcxx-testing<br/>(major-only)"] …
```
> LLVM v19.1.1

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
- .ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.8.yaml
- .ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.5.yaml
- .ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
- .ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.8.yaml
- .ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.5.yaml
- .ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.5.yaml
- .ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.5.yaml
- .ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.5.yaml
- .ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.5.yaml
- .scripts/run_osx_build.sh
- README.md
- build-locally.py
- recipe/conda_build_config.yaml
- recipe/meta.yaml
Arrows indicate dependencies. This PR depends on everything under "core dependencies" to be completed. The boxes are clickable and refer to the respective PRs – if the box is green, the PR has been merged (colours are not updated automatically).
```mermaid
---
config:
---
%% to update: change links of PRs at the bottom (once, when creating the PR)
%% to mark things as done, move things from `classDef <name> baseNode;` to `classDef <name> doneNode;`
flowchart TB
subgraph core["core&nbsp;dependencies"]
hidden1~~~libcxx["libcxx"]
hidden1~~~llvmdev["llvmdev"]
llvmdev-->clangdev["clangdev"]
libcxx-->clangdev
llvmdev-->lld["lld"]
clangdev-->compiler-rt["compiler-rt"]
clangdev-->cctools["cctools<br/>(major-only)"]
compiler-rt-->openmp["openmp"]
end
%% sort this before …
```
> LLVM v19.1.5

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64version21.1.0.rc2.yaml
- .ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64version21.1.0.rc2.yaml
- .ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64version21.1.0.rc2.yaml
- .ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64version21.1.0.rc2.yaml
- .ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64version21.1.0.rc2.yaml
- .ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64version21.1.0.rc2.yaml
- README.md
- recipe/conda_build_config.yaml
Clang v20.1 for other platforms (major-only):
> LLVM v21.1.0.rc2
