conda-forge/clang-compiler-activation-feedstock

recipe/activate-clang.sh
recipe/meta.yaml

Checklist
`conda smithy rerender` ended with :
> No changes made. This feedstock is up-to-date.
Closes conda-forge/clang-compiler-activation-feedstock#18
Having this variable set prevents using the system `codesign` to sign binaries.
Don't set it.

activate-clang: don't set CODESIGN_ALLOCATE

---

recipe/activate-clang++.sh
recipe/activate-clang.sh
recipe/build.sh
recipe/deactivate-clang++.sh
recipe/deactivate-clang.sh
recipe/meta.yaml

This is needed because r-base brings in the compiler for build platform
when cross-compiling which is undesirable
Checklist

Don't activate if the target_platform is unexpected

---

recipe/activate-clang++.sh
recipe/activate-clang.sh
recipe/deactivate-clang++.sh
recipe/deactivate-clang.sh
recipe/meta.yaml

Fix condition

---

README.md
recipe/meta.yaml

Fixes #49 
`clang_bootstrap_` is currently not working on `osx-arm64` as the code signatures are invalid. This fixes it by adding `cctools` to all build environments so that `conda-build` will pick up the right tools on correcting paths.
Checklist

Fix macOS code signatures

---

.azure-pipelines/azure-pipelines-linux.yml
recipe/activate-clang.sh
recipe/deactivate-clang.sh
recipe/meta.yaml

Upstream cctools does not support `indr` anymore, see [this](https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/63#issuecomment-880241992) comment.
Closes #63 
Closes #62

clang-compiler-activation v12.0.1 (redux)

---

README.md
recipe/build.sh
recipe/meta.yaml

Remove std=c++14 from flags

---

recipe/conda_build_config.yaml
recipe/meta.yaml

Manual PR because the bot doesn't work anymore now that this recipe has several LLVM versions at the same time.
Blockers for merging this PR and thus enabling the compilers in conda-forge (indentation denotes dependency; c.f. list from [14.x](https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/82#issue-1178735569)):
The PRs marked ** are not strictly speaking necessary for merging this PR, but for LLVM 15.x support in conda-forge.
[^1]: though really openmp/lld/compiler-rt had been blocked on https://github.com/conda-forge/llvmdev-feedstock/pull/190

LLVM 15.0.7

---

recipe/activate-clang.sh
recipe/meta.yaml

meson will not auto-discover cmake/pkgconfig in the context of cross-compilation; it needs to be specified explicitly; same goes for the pkgconfig-metadata.
Add this to the default `meson_cross_file.txt` that's generated for our osx cross-compilation, so we don't have to add this manually (like in https://github.com/conda-forge/scipy-feedstock/pull/205 currently).
I _presume_ that the presence of these extra lines should not affect cross-compilation cases where either `cmake` or `pkgconfig` is not actually available. Perhaps @eli-schwartz can confirm/deny?
In any case, would appreciate your inputs @isuruf

extend ${BUILD_PREFIX}/meson_cross_file.txt with pkgconfig & cmake setup

---

recipe/meta.yaml

Ensure that compilers can be co-installed with the new libcxx in the same environment

Rebuild for libxml2

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.5.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.5.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.5.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.5.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.5.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.5.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

This is [planned](https://discourse.llvm.org/t/16-0-5-releae/71097) to be the last release in the 16.0.x series.

LLVM 16.0.5

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Announced as the last[^1] [planned](https://discourse.llvm.org/t/16-0-6-release/71344) release in the 16.0.x series
[^1]: same as 16.0.5

LLVM 16.0.6

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.0.rc1.yaml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.0.rc1.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version15.0.7.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version15.0.7.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.0.rc1.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.0.rc1.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version15.0.7.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version15.0.7.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.0.rc1.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.0.rc1.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version15.0.7.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version15.0.7.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.scripts/run_osx_build.sh
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

This time I came prepared 😎 
Blockers for merging this PR and thus enabling the compilers in conda-forge (indentation denotes dependency; c.f. list from [16.x](https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/99)):
The PRs marked ** are not strictly speaking necessary for merging this PR, but for LLVM 17.x support in conda-forge.

LLVM 17.0.0.rc1

---

.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_osx_build.sh
recipe/meta.yaml

Pick up fix from https://github.com/conda-forge/compiler-rt-feedstock/pull/89 also for the bootstrap compilers.

Fix compiler-rt path

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version15.0.7.yaml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version15.0.7.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version15.0.7.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version15.0.7.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version15.0.7.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version15.0.7.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
README.md
recipe/conda_build_config.yaml
recipe/install-clang.sh
recipe/install-clangxx.sh
recipe/meta.yaml

Blockers for merging this PR and thus enabling the compilers in conda-forge (indentation denotes dependency; c.f. list from [16.x](https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/99)):
Related feedstocks for LLVM 17 support more generally:

LLVM 17.0.6

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.0.rc1.yaml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.0.rc1.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.0.rc1.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.0.rc1.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.0.rc1.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.0.rc1.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.gitignore
.scripts/build_steps.sh
.scripts/run_docker_build.sh
README.md
recipe/build.sh
recipe/conda_build_config.yaml
recipe/install-clang.sh
recipe/install-clangxx.sh
recipe/meta.yaml

Blockers for merging this PR and thus enabling the compilers in conda-forge (indentation denotes dependency; c.f. list from [17.x](https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/113)):
Related feedstocks for LLVM 18 support more generally:

LLVM 18.1.0.rc1

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.0.rc4.yaml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.0.rc4.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.0.rc4.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.0.rc4.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.0.rc4.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.0.rc4.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
build-locally.py
conda-forge.yml
recipe/conda_build_config.yaml
recipe/meta.yaml

Blockers for merging this PR and thus enabling the compilers in conda-forge (indentation denotes dependency; c.f. list from [17.x](https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/113)):
Related feedstocks for LLVM 18 support more generally:

LLVM 18.1.0.rc4

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.2.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.2.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.2.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.2.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.2.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.2.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Blockers for merging this PR and thus enabling the compilers in conda-forge (indentation denotes dependency; c.f. list from [17.x](https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/113)):
Related feedstocks for LLVM 18 support more generally:

LLVM 18.1.2

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.3.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.3.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.3.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.3.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.3.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.3.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Blockers for merging this PR and thus enabling the compilers in conda-forge (indentation denotes dependency; c.f. list from [17.x](https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/113), not counting PRs only needed for new major version):
Related feedstocks for LLVM 18.1.3 support more generally:

LLVM 18.1.3

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.5.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.5.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.5.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.5.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version16.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.5.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version16.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.5.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Blockers for merging this PR and thus enabling the compilers in conda-forge (indentation denotes dependency; c.f. list from #123):
Related feedstocks for LLVM 18.1.4 support more generally:

LLVM 18.1.5

---

recipe/meta.yaml

Now that https://github.com/conda-forge/libcxx-feedstock/pull/131 has finally been merged, support its use with the cxx compilers. We cannot yet go back to the pre-17 days of just requiring `version` for libcxx directly (c.f. https://github.com/conda-forge/clang-compiler-activation-feedstock/commit/db8e474173b3735d91c5de7d261a5911c78db516) until we also have [libcxx 18](https://github.com/conda-forge/libcxx-feedstock/pull/144), which might still take a little while.
Also, holding off on the release of 18 allows us to judge the impact of libcxx 17 on the broader ecosystem a bit better (and adapt to deprecations etc. as necessary), rather than jumping by 2 major versions in one go.

support using libcxx 17

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.7.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.7.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.7.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.7.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.7.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.7.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Related feedstocks for LLVM 18.1.7 support more generally:

LLVM 18.1.7

---

recipe/install-clang.sh
recipe/meta.yaml

In https://github.com/conda-forge/openjdk-feedstock/pull/167, the build checks presence and functionality of the preprocessor. For linux, this is handled as `CPP=${CXX_FOR_BUILD//+/p}`, where `CXX_FOR_BUILD` generally uses the `$TRIPLE-<name>` style.
We're similarly setting
https://github.com/conda-forge/clang-compiler-activation-feedstock/blob/04e155656a0b3604bc2f0c2fc14484dbac7c3349/recipe/build.sh#L29-L30
here, but contrary to [`gcc_impl_linux-<arch>`](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Fgcc_impl_linux-64-14.1.0-h3c94d91_0.conda), we don't have a `$TRIPLE`-preprocessor for clang. Since the symlink structure is not the same for gcc & clang anyway (c.f. #118), add a symlink here for `$TRIPLE-clang-cpp`, like we do for `$TRIPLE-clang` already.

add symlinks for $TRIPLE-clang-cpp

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag-Dbuildtype=releaseversion19.1.0.yaml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag-Dbuildtype=releaseversion19.1.0.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag--buildtype_releaseversion16.0.6.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag-Dbuildtype=releaseversion17.0.6.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag-Dbuildtype=releaseversion18.1.8.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag--buildtype_releaseversion16.0.6.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag-Dbuildtype=releaseversion17.0.6.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag-Dbuildtype=releaseversion18.1.8.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag-Dbuildtype=releaseversion19.1.0.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag-Dbuildtype=releaseversion19.1.0.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag--buildtype_releaseversion16.0.6.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag-Dbuildtype=releaseversion17.0.6.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag-Dbuildtype=releaseversion18.1.8.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag--buildtype_releaseversion16.0.6.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag-Dbuildtype=releaseversion17.0.6.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag-Dbuildtype=releaseversion18.1.8.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag-Dbuildtype=releaseversion19.1.0.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag-Dbuildtype=releaseversion19.1.0.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag--buildtype_releaseversion16.0.6.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag-Dbuildtype=releaseversion17.0.6.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag-Dbuildtype=releaseversion18.1.8.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag--buildtype_releaseversion16.0.6.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag-Dbuildtype=releaseversion17.0.6.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag-Dbuildtype=releaseversion18.1.8.yaml
.scripts/build_steps.sh
README.md
recipe/conda_build_config.yaml

Related feedstocks for LLVM 19.1.0 support more generally:

LLVM 19.1.0.rc1

---

recipe/conda_build_config.yaml
recipe/meta.yaml

We've finally caught back up after https://github.com/conda-forge/libcxx-feedstock/pull/155 got merged. 🙃 
C.f. list in #131 (resp. #113 before #128)

Reinstate libcxx version that matches compiler 

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag-Dbuildtype=releaseversion19.1.0.rc3.yaml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag-Dbuildtype=releaseversion19.1.0.rc3.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag-Dbuildtype=releaseversion19.1.0.rc3.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag-Dbuildtype=releaseversion19.1.0.rc3.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0meson_release_flag-Dbuildtype=releaseversion19.1.0.rc3.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0meson_release_flag-Dbuildtype=releaseversion19.1.0.rc3.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Related feedstocks for LLVM 19.1.0 support more generally:

LLVM 19.1.0.rc3

---

recipe/activate-clang.sh
recipe/meta.yaml

since we are using crossenv, meson thinks we can run the executables
Checklist

set needs_exe_wrapper for cross-compile

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.2.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.2.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.2.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.2.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.2.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.2.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
azure-pipelines.yml
recipe/conda_build_config.yaml
recipe/meta.yaml

Clang 19.1 for other platforms (major-only):
```mermaid
---
config:
---
flowchart TD
subgraph core["core&nbsp;dependencies"]
hidden1~~~llvmdev["☑ llvmdev"]
hidden1~~~libcxx["☑ libcxx"]
llvmdev-->clangdev["☑ clangdev"]
libcxx-->clangdev
llvmdev-->lld["☑ lld"]
clangdev-->compiler-rt["☑ compiler-rt"]
clangdev-->cctools["☑ cctools<br/>(major-only)"]
compiler-rt-->openmp["☑ openmp"]
end
subgraph clangs["other&nbsp;clang&nbsp;compilers"]
hidden2~~~clang_linux["☐ clang_linux<br/>(major-only)"]
clang_linux~~~clang_win["☑ clang_win<br/>(major-only)"]
clang_win~~~r_clang["☑ r_clang<br/>(major-only)"]
end
compiler-rt-->flang
subgraph …
```

LLVM v19.1.2

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.3.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.3.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.3.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.3.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.3.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.3.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Arrows indicate dependencies. This PR depends on everything under "core dependencies" to be completed. The boxes are clickable and refer to the respective PRs – if the box is green, the PR has been merged (colours are not updated automatically).
```mermaid
---
config:
---
%% to update: change links of PRs at the bottom (once, when creating the PR)
%% to mark things as done, move things from `classDef <name> baseNode;` to `classDef <name> doneNode;`
flowchart TD
subgraph core["core&nbsp;dependencies"]
hidden1~~~libcxx["libcxx"]
hidden1~~~llvmdev["llvmdev"]
llvmdev-->clangdev["clangdev"]
libcxx-->clangdev
llvmdev-->lld["lld"]
clangdev-->compiler-rt["compiler-rt"]
clangdev-->cctools["cctools<br/>(major-only)"]
compiler-rt-->openmp["openmp"]
end
subgraph …
```

LLVM v19.1.3

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.6.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.6.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.6.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.6.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Arrows indicate dependencies. This PR depends on everything under "core dependencies" to be completed. The boxes are clickable and refer to the respective PRs – if the box is green, the PR has been merged (colours are not updated automatically).
```mermaid
---
config:
---
%% to update: change links of PRs at the bottom (once, when creating the PR)
%% to mark things as done, move things from `classDef <name> baseNode;` to `classDef <name> doneNode;`
flowchart TB
subgraph core["core&nbsp;dependencies"]
hidden1~~~libcxx["libcxx"]
hidden1~~~llvmdev["llvmdev"]
llvmdev-->clangdev["clangdev"]
libcxx-->clangdev
llvmdev-->lld["lld"]
clangdev-->compiler-rt["compiler-rt"]
clangdev-->cctools["cctools<br/>(major-only)"]
compiler-rt-->openmp["openmp"]
end
%% sort this before …
```

LLVM v19.1.6

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.7.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.7.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.7.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.7.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.7.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.7.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Github broke the mermaid rendering, so it's back to list-only
Clang 19.1 for other platforms (major-only):

LLVM v19.1.7

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version20.1.0.rc1.yaml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version20.1.0.rc1.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.8.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.7.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.8.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.7.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version20.1.0.rc1.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version20.1.0.rc1.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.8.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.7.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.8.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.7.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version20.1.0.rc1.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version20.1.0.rc1.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version17.0.6.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version18.1.8.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version19.1.7.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version17.0.6.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version18.1.8.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version19.1.7.yaml
.gitignore
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Github broke the mermaid rendering, so it's back to list-only
Clang v20.1 for other platforms (major-only):

LLVM v20.1.0.rc1

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version20.1.2.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version20.1.2.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version20.1.2.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version20.1.2.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version20.1.2.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version20.1.2.yaml
.scripts/run_docker_build.sh
README.md
build-locally.py
recipe/conda_build_config.yaml
recipe/meta.yaml

Github broke the mermaid rendering, so it's back to list-only

LLVM v20.1.2

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version20.1.3.yaml
.ci_support/linux_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version20.1.3.yaml
.ci_support/osx_64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version20.1.3.yaml
.ci_support/osx_64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version20.1.3.yaml
.ci_support/osx_arm64_cross_target_platformosx-64macos_machinex86_64-apple-darwin13.4.0version20.1.3.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64macos_machinearm64-apple-darwin20.0.0version20.1.3.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Github broke the mermaid rendering, so it's back to list-only
The [readdition](https://github.com/llvm/llvm-project/pull/134158/files) of `_LIBCPP_DISABLE_AVAILABILITY` (c.f. #153) missed this release. Also, lldb & mlir-python are still blocked due to https://github.com/conda-forge/libcxx-feedstock/issues/220 - help is welcome there!

LLVM v20.1.3

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64version20.1.5.yaml
.ci_support/linux_64_cross_target_platformosx-arm64version20.1.5.yaml
.ci_support/osx_64_cross_target_platformosx-64version20.1.5.yaml
.ci_support/osx_64_cross_target_platformosx-arm64version20.1.5.yaml
.ci_support/osx_arm64_cross_target_platformosx-64version20.1.5.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64version20.1.5.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

The [readdition](https://github.com/llvm/llvm-project/commit/be087ab35970dffe3e473b5a10266ed356261746) of `_LIBCPP_DISABLE_AVAILABILITY` (c.f. #153) finally landed after missing a couple of patch releases... I've got my fingers crossed that this might potentially fix https://github.com/conda-forge/libcxx-feedstock/issues/220 and thus also lldb and mlir-python 🤞 

LLVM v20.1.5

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64version20.1.6.yaml
.ci_support/linux_64_cross_target_platformosx-arm64version20.1.6.yaml
.ci_support/osx_64_cross_target_platformosx-64version20.1.6.yaml
.ci_support/osx_64_cross_target_platformosx-arm64version20.1.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-64version20.1.6.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64version20.1.6.yaml
README.md
recipe/conda_build_config.yaml
recipe/install-clang_impl.sh
recipe/install-clangxx_impl.sh
recipe/meta.yaml

The [readdition](https://github.com/llvm/llvm-project/commit/be087ab35970dffe3e473b5a10266ed356261746) of `_LIBCPP_DISABLE_AVAILABILITY` (c.f. #153) finally landed after missing a couple of patch releases... I've got my fingers crossed that this might potentially fix https://github.com/conda-forge/libcxx-feedstock/issues/220 and thus also lldb and mlir-python 🤞 

LLVM v20.1.6

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64version21.1.0.rc1.yaml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64version21.1.0.rc1.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-64version19.1.7.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-64version20.1.8.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64version19.1.7.yaml
.ci_support/linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64version20.1.8.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64version21.1.0.rc1.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64version21.1.0.rc1.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-64version19.1.7.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-64version20.1.8.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-arm64version19.1.7.yaml
.ci_support/osx_64_channel_targetsconda-forge_maincross_target_platformosx-arm64version20.1.8.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64version21.1.0.rc1.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64version21.1.0.rc1.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-64version19.1.7.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-64version20.1.8.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-arm64version19.1.7.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_maincross_target_platformosx-arm64version20.1.8.yaml
.gitattributes
README.md
recipe/conda_build_config.yaml

A new feedstock joins the party, now we have flang-rt too. :)
Clang v20.1 for other platforms (major-only):

LLVM v21.1.0.rc1

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64version21.1.0.rc3.yaml
.ci_support/linux_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64version21.1.0.rc3.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64version21.1.0.rc3.yaml
.ci_support/osx_64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64version21.1.0.rc3.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-64version21.1.0.rc3.yaml
.ci_support/osx_arm64_channel_targetsconda-forge_llvm_rccross_target_platformosx-arm64version21.1.0.rc3.yaml
README.md
recipe/conda_build_config.yaml

Clang v21.1 for other platforms (major-only):

LLVM v21.1.0.rc3

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformosx-64version19.1.7.yaml
.ci_support/linux_64_cross_target_platformosx-64version20.1.8.yaml
.ci_support/linux_64_cross_target_platformosx-64version21.1.0.yaml
.ci_support/linux_64_cross_target_platformosx-arm64version19.1.7.yaml
.ci_support/linux_64_cross_target_platformosx-arm64version20.1.8.yaml
.ci_support/linux_64_cross_target_platformosx-arm64version21.1.0.yaml
.ci_support/osx_64_cross_target_platformosx-64version19.1.7.yaml
.ci_support/osx_64_cross_target_platformosx-64version20.1.8.yaml
.ci_support/osx_64_cross_target_platformosx-64version21.1.0.yaml
.ci_support/osx_64_cross_target_platformosx-arm64version19.1.7.yaml
.ci_support/osx_64_cross_target_platformosx-arm64version20.1.8.yaml
.ci_support/osx_64_cross_target_platformosx-arm64version21.1.0.yaml
.ci_support/osx_arm64_cross_target_platformosx-64version19.1.7.yaml
.ci_support/osx_arm64_cross_target_platformosx-64version20.1.8.yaml
.ci_support/osx_arm64_cross_target_platformosx-64version21.1.0.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64version19.1.7.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64version20.1.8.yaml
.ci_support/osx_arm64_cross_target_platformosx-arm64version21.1.0.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Clang v21.1 for other platforms (major-only):

LLVM v21.1.0
